FROM ghcr.io/cirruslabs/flutter:3.29.3 AS builder

WORKDIR /app

COPY pubspec.yaml ./
RUN flutter pub get

COPY . .
RUN flutter build web --release

FROM nginx:1.27-alpine AS runner

COPY build/web /usr/share/nginx/html

EXPOSE 80
