FROM ghcr.io/cirruslabs/flutter:3.29.3 AS builder

WORKDIR /app

COPY pubspec.yaml ./
RUN flutter pub get

COPY . .
RUN flutter build web --release

FROM nginx:1.27-alpine AS runner

ENV APP_NAME=CloudTodo Web
ENV APP_ENV=production
ENV API_BASE_URL=http://localhost:3000/api

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint-config.sh /docker-entrypoint.d/30-config.sh
RUN chmod +x /docker-entrypoint.d/30-config.sh
COPY build/web /usr/share/nginx/html

EXPOSE 80
